#-*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1rfeHp5nea9yQ2hziyOOGjeq5k6-w9x5v
"""

#import libraries
import pandas as pd
import numpy
import sklearn
import matplotlib.pyplot as plt
from matplotlib import style
from sklearn import linear_model
from sklearn.utils import shuffle
import datetime
import seaborn as sns

##Set up the data file and the parameters you want to use
File = pd.read_csv("C:/Users/Gebruiker/PycharmProjects/D4GC/Animals/danger.csv",sep=",")
Animals = File[["date","all_m","all_b","all_r","all_am","all_f","all_s","all_cl","all_mo","all_cr","all_i","all_ar","all_co",
    "all_p","all_ani","all_all","end_m","thrt_m","end_b","thrt_b","end_r","thrt_r","end_am","thrt_am","end_f","thrt_f",
             "end_s","thrt_s","end_cl","thrt_cl","end_mo","thrt_mo","end_cr","thrt_cr","end_i","thrt_i","end_ar",
             "thrt_ar","end_co","thrt_co","end_p","thrt_p","end_ani","thrt_ani","end_all","thrt_all","fires","acres"]]

#%%
Animals['datetime'] = pd.to_datetime(Animals['date'], infer_datetime_format=True)

#%%
#plants
sns.lineplot(x=Animals.datetime, y=Animals.all_p)
ax2 = plt.twinx()
sns.lineplot(x=Animals.datetime, y=Animals.fires, color="r", ax=ax2)

plt.show()


#%%
#animals
sns.lineplot(x=Animals.datetime, y=Animals.all_ani)
ax3 = plt.twinx()
sns.lineplot(x=Animals.datetime, y=Animals.fires, color="r", ax=ax3)

plt.show()

